services:
  docs:
    image: sw_task_local_docs
    container_name: sw_task_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./sw_task:/app/sw_task:z
    ports:
      - '9000:9000'
    command: /start-docs
